#!/bin/sh

# Define modifier as "Super" aka Logo, GUI, Win, Mod4.
mod="Super"

# Start Foot terminal emulator.
riverctl map normal $mod+Shift Return spawn foot

# Close the focused view.
riverctl map normal $mod Q close

# Exit River.
riverctl map normal $mod+Shift E exit

# Focus the next/previous view in the layout stack.
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Swap the focused view with the next/previous view in the layout stack.
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Focus the next/previous output.
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# Send the focused view to the next/previous output.
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# Bump the focused view to the top of the layout stack.
riverctl map normal $mod Return zoom

# Decrease/increase the main ratio of Rivertile.
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

# Increment/decrement the main count of Rivertile.
riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

# Move views.
riverctl map normal $mod+Alt H move left 100
riverctl map normal $mod+Alt J move down 100
riverctl map normal $mod+Alt K move up 100
riverctl map normal $mod+Alt L move right 100

# Snap views to screen edges.
riverctl map normal $mod+Alt+Control H snap left
riverctl map normal $mod+Alt+Control J snap down
riverctl map normal $mod+Alt+Control K snap up
riverctl map normal $mod+Alt+Control L snap right

# Resize views.
riverctl map normal $mod+Alt+Shift H resize horizontal -100
riverctl map normal $mod+Alt+Shift J resize vertical 100
riverctl map normal $mod+Alt+Shift K resize vertical -100
riverctl map normal $mod+Alt+Shift L resize horizontal 100

# Move views.
riverctl map-pointer normal $mod BTN_LEFT move-view

# Resize views.
riverctl map-pointer normal $mod BTN_RIGHT resize-view

# Toggle float.
riverctl map-pointer normal $mod BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Focus tag [0-8].
    riverctl map normal $mod $i set-focused-tags $tags

    # Tag focused view with tag [0-8].
    riverctl map normal $mod+Shift $i set-view-tags $tags

    # Toggle focus of tag [0-8].
    riverctl map normal $mod+Control $i toggle-focused-tags $tags

    # Toggle tag [0-8] of focused view.
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))

# Focus all tags.
riverctl map normal $mod 0 set-focused-tags $all_tags

# Tag focused view with all tags.
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Toggle float.
riverctl map normal $mod Space toggle-float

# Toggle full-screen.
riverctl map normal $mod F toggle-fullscreen

# Change layout orientation.
riverctl map normal $mod Up    send-layout-cmd rivertile "main-location top"
riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
riverctl map normal $mod Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod Left  send-layout-cmd rivertile "main-location left"

# Declare pass-through mode.
riverctl declare-mode passthrough

# Enter pass-through mode.
riverctl map normal $mod F11 enter-mode passthrough

# Return to normal mode.
riverctl map passthrough $mod F11 enter-mode normal

# Set background and border colors.
riverctl background-color 0x002B36
riverctl border-color-focused 0x93A1A1
riverctl border-color-unfocused 0x586E75

# Set keyboard repeat rate.
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add float -app-id 'float*' -title 'foo'

# Make all views with app-id "bar" and any title use client-side decorations.
riverctl rule-add csd -app-id "bar"

# Set the default layout generator to be Rivertile and start it.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &
